Notification::PostingValidationInfoPresenter = Class.new(NotificationPresenter)
Notification::PostingVolumePresenter = Class.new(NotificationPresenter)
Notification::EbaymPresenter = Class.new(NotificationPresenter)
Notification::CraigPresenter = Class.new(NotificationPresenter)
Notification::HmngsPresenter = Class.new(NotificationPresenter)
Notification::RemlsPresenter = Class.new(NotificationPresenter)
