module DataConverters
  module BackPage
    module CategoriesData
      RELATION_CHILD_CATEGORY_TO_FULLSUFFIX = {
      	'COMM' => ['local places: events', 'local places: bars/clubs', 'local places: restaurants','community: classes/workshops','community: general','community: groups', 'buy: yard sales', 'sell: yard sales', 'trade: yard sales', 'musician: plug the band'],
				'SVCM' => ['local places: salons/nails/spas','local places: hair salons/nails/spas'],
				'SVCH' =>	['community: childcare'],	
				'CLNF' =>	['community: lost & found'],
				'JVOL' =>	['community: volunteers'],
				'SANT' =>	['buy, sell, trade: antiq.-collectibles', 'buy, sell, trade: antiques for sale'],
				'SAPL' => ['buy, sell, trade: appliances', 'buy, sell, trade: electronics', 'buy, sell, trade: appliances for sale'],
				'SAPP' => ['buy, sell, trade: clothing for sale'],
				'SBIZ' => ['buy, sell, trade: business for sale'],
				'SIND' =>	['buy, sell, trade: business'],
				'VOTH' =>	['buy, sell, trade: boat & motorcycle', 'buy, sell, trade: boats & motorcycles'],
				'SJWL' =>	['buy, sell, trade: clothing/jewelry'],	
				'SELE' =>	['buy, sell, trade: computer/electronics'],
				'SHNG' => ['buy, sell, trade: farm/garden', 'buy, sell, trade: household items', 'buy, sell, trade: farm & garden', 'buy, sell, trade: yard sales'],
				'SOTH' =>	['buy, sell, trade: free', 'buy, sell, trade: miscellaneous'],
				'SFUR' =>	['buy, sell, trade: furniture', 'buy, sell, trade: furniture for sale'],
				'ASUP' =>	['buy, sell, trade: pets, pet supplies', 'buy, sell, trade: pets for sale'],
				'SSNF' => ['buy, sell, trade: sports equip.', 'buy, sell, trade: sports equipment for sale'],
				'STIX' =>	['buy, sell, trade: tickets', 'buy, sell, trade: tickets for sale'],
				'STOO' =>	['buy, sell, trade: tools/materials', 'buy, sell, trade: tools for sale'],
				'SWNT' => ['buy, sell, trade: want-trade'],
				'VAUT' =>	['automotive: auto-truck-rv', 'automotive: autos for sale'],
				'VPAR' => ['automotive: auto parts'],
				'SVCP' =>	['automotive: services', 'automotive: automotive services'],
				'JGIG' =>	['musician: available/wanted', 'musician: musicians available/wanted'],
				'SMUS' =>	['musician: equip/instruments', 'musician: music equipment/instruments'],
				'SVCC' =>	['musician: instruction', 'musician: music instruction', 'musician: services', 'musician: musicians services'],
				'RSHR' =>	['rentals: roommates'],
				'RHFR' =>	['rentals: apt/condo/house', 'rentals: miscellaneous', 'rentals: apartments & houses for rent'],
				'RCRE' =>	['rentals: commercial'],
				'RVAC' =>	['rentals: vacation'],
				'RWNT' => ['rentals: rentals wanted', 'real estate: wanted', 'real estate for sale: real estate wanted'],
				'RHFS' =>	['real estate: house/condo', 'real estate for sale: homes for sale'],
				'RLOT' =>	['real estate: land for sale', 'real estate for sale: land for sale'],
				'RCRE' =>	['real estate: commercial', 'real estate for sale: commercial'],
				'ROTH' =>	['real estate: misc', 'real estate for sale: miscellaneous'],
				'JFIN' =>	['jobs: acctg/finance'],
				'JADM' =>	['jobs: admin/office', 'jobs: administrative & office jobs'],
				'JWEB' => ['jobs: computer/technical', 'jobs: computer/technical jobs'],
				'JCUS' => ['jobs: customer service', 'jobs: customer service jobs'],
				'JSKL' => ['jobs: domestic', 'jobs: domestic jobs', 'jobs: focus group/studies', 'jobs: trades/labor', 'jobs: trades & labor jobs'],
				'JOPS' =>	['jobs: driver/delivery/courier', 'jobs: driver/delivery/courier jobs'],
				'JEDU' =>	['jobs: education', 'jobs: education jobs'],
				'JRES' => ['jobs: job wanted/resume'],
				'JMAN' =>	['jobs: mgmt/professional', 'jobs: management/professional jobs'],
				'JHEA' =>	['jobs: medical/health', 'jobs: medical/health jobs'],
				'JOTH' =>	['jobs: miscellaneous', 'jobs: part-time jobs', 'jobs: miscellaneous jobs'],
				'JREA' => ['jobs: real estate', 'jobs: real estate jobs'],
				'JHOS' =>	['jobs: rest/retail/hotel', 'jobs: restaurant, retail, hotel jobs'],
				'JMAR' =>	['jobs: sales/mktg', 'jobs: sales & marketing jobs'],
				'JBEA' =>	['jobs: salon/spa', 'jobs: salon/spa jobs'],
				'JENT' =>	['jobs: show biz/audition'],
				'JACC' => ['accounting/financial jobs'],
				'DISC' => ['forums: arts & ent', 'forums: computer', 'forums: employment', 'forums: gay', 'forums: legal', 'forums: lesbian', 'forums: misc.', 'forums: music', 'forums: pet', 'forums: politics', 'forums: religion', 'forums: sex', 'forums: sports'],
				'PWSM' =>	['dating: women > men', 'dating: men > women', 'dating: men > men', 'dating: women > women'],
				'MADU' => ['adult: escorts', 'adult: body rubs', 'adult: strippers & strip clubs', 'adult: dom & fetish', 'adult: ts', 'adult: male escorts', 'adult: phone & websites', 'adult: adult jobs'],
				'SVCP' =>	['services: biz opps', 'services: business opportunities', 'services: business', 'services: business services', 'services: computer', 'services: home improvement', 'services: labor/moving', 'services: legal', 'services: legal services', 'services: real estate', 'services: real estate services'],
				'SVCH' => ['services: cleaning', 'services: cleaning services', 'services: landscape/lawn', 'services: landscape/lawn services'],
				'SVCC' =>	['services: creative', 'services: creative services'],
				'SVCF' =>	['services: financial'],
				'SVCM' =>	['services: health & beauty', 'services: massage', 'services: therapeutic massage', 'services: health/beauty services'],
				'SVCO' =>	['services: misc.','services: misc. services']
      } 
    end
  end
end    	