module DataConverters
  module Html
    module CraigData
      CRAIG_PARENT_TO_CHILD_CATEGORY ={
        'ccc' => %w(pet laf eve cls act com grp rid vnn pol vol ats muc kid),
        'sss' => %w(gms ard art atd atq ppd app cld clo bar bik bid bfd bfs cbd clt syd sys mob mod eld ele phd pho vgm vgd fud fuo hab had grq grd hsd hsh mad mat jwd jwl bad bab bkd bks emq emd msd msg fod for zip sgd spo tid tix tld tls tad tag wan ctd cto mcd mcy rvs rvd bod boa ptd pts),
        'ggg' => %w(crg cwg dmg evg lbg tlg wrg cpg),
        'hhh' => %w(off nfa fee nfb abo aiv reb reo prk roo sbw sub swp vac hou rew sha), 
        'jjj' => %w(ofc spa sls csr tch med edu egr tfr acc fbh gov hea hum lgl bus mar mnu npo etc rej ret sci sec lab trd trp eng sof sad web wri),
        'ppp' => %w(rnr cas m4m msr mis m4w w4m stp w4w),
        'res' => %w(res),
        'bbb' => %w(trv wet lss fns fgs hss bts ths thp aos cps cys evs lbs lgs mas pas rts sks biz crs)
      }  

      CRAIG_PARENT_SUB_TO_CHILD_CATEGORY ={
        'cal' => %w(eve cls),
        'ara' => %w(ard art),
        'ata' => %w(atd atq),
        'ppa' => %w(ppd app),
        'cla' => %w(cld clo),
        'bia' => %w(bik bid),
        'bfa' => %w(bfd bfs),
        'cba' => %w(cbd clt),
        'sya' => %w(syd sys),
        'moa' => %w(mob mod),
        'ela' => %w(eld ele),
        'pha' => %w(phd pho),
        'vga' => %w(vgm vgd),
        'fua' => %w(fud fuo),
        'haa' => %w(hab had),
        'gra' => %w(grq grd),
        'hsa' => %w(hsd hsh),
        'maa' => %w(mad mat),
        'jwa' => %w(jwd jwl),
        'baa' => %w(bad bab),
        'bka' => %w(bkd bks),
        'ema' => %w(emq emd),
        'msa' => %w(msd msg),
        'foa' => %w(fod for),
        'sga' => %w(sgd spo),
        'tia' => %w(tid tix),
        'tla' => %w(tld tls),
        'taa' => %w(tad tag),
        'cta' => %w(ctd cto),
        'mca' => %w(mcd mcy),
        'rva' => %w(rvs rvd),
        'boo' => %w(bod boa),
        'pta' => %w(ptd pts),
        'apa' => %w(nfa fee nfb abo aiv),
        'rea' => %w(reb reo),
        'hsw' => %w(sbw hou rew sha)
      }  



      CRAIG_CHILD_AND_PARENT_CATEGORY_TO_3TAPS_CHILD_CATEGORY ={
        'APET' => %w(pet),
        'CLNF' => %w(laf),
        'COMM' => %w(eve cls act com grp gms cal),   
        'CRID' => %w(rid),
        'DISC' => %w(vnn pol rnr),    
        'JVOL' => %w(vol),
        'SVCC' => %w(ats muc kid wet crs),
        'SANC' => %w(ard art ara),
        'SANT' => %w(atd atq),   
        'SAPL' => %w(ppd app ppa),
        'SAPP' => %w(cld clo cla),
        'SBAR' => %w(bar),
        'SBIK' => %w(bik bid bia),
        'SBIZ' => %w(bfd bfs bfa),
        'SCOL' => %w(cbd clt cba),    
        'SELE' => %w(syd sys mob mod eld ele phd pho vgm vgd sya moa ela pha vga), 
        'SFUR' => %w(fud fuo fua),    
        'SHNB' => %w(hab had haa),
        'SHNG' => %w(grq grd hsd hsh gra hsa),
        'SIND' => %w(mad mat maa),   
        'SJWL' => %w(jwd jwl jwa),   
        'SKID' => %w(bad bab baa),    
        'SLIT' => %w(bkd bks bka),
        'SMNM' => %w(emq emd ema),
        'SMUS' => %w(msd msg msa),
        'SOTH' => %w(fod for zip foa),
        'SSNF' => %w(sgd spo sga),
        'STIX' => %w(tid tix tia),
        'STOO' => %w(tld tls tad tag tla),
        'STOY' => %w(tad tag taa),    
        'SWNT' => %w(wan),
        'VAUT' => %w(ctd cto mcd mcy rvs rvd cta mca rva),  
        'VOTH' => %w(bod boa boo),    
        'VPAR' => %w(ptd pts pta),
        'JGIG' => %w(crg cwg dmg evg lbg tlg wrg),
        'WEB'  => %w(cpg),
        'RCRE' => %w(off),
        'RHFR' => %w(nfa fee nfb abo aiv apa),
        'RHFS' => %w(reb reo rea),
        'RPNS' => %w(prk),
        'RSHR' => %w(roo),
        'RSUB' => %w(sbw sub hsw),
        'RSWP' => %w(swp),
        'RVAC' => %w(vac),
        'RWNT' => %w(hou rew sha hsw),
        'JADM' => %w(ofc),
        'JBEA' => %w(spa),
        'JBIZ' => %w(sls),
        'JCUS' => %w(csr tch),
        'JDES' => %w(med),
        'JEDU' => %w(edu),
        'JENG' => %w(egr),
        'JENT' => %w(tfr),
        'JFIN' => %w(acc),
        'JFNB' => %w(fbh),
        'JGOV' => %w(gov),
        'JHEA' => %w(hea),
        'JHUM' => %w(hum),
        'JLEG' => %w(lgl),
        'JMAN' => %w(bus),
        'JMAR' => %w(mar),
        'JMFT' => %w(mnu),
        'JNON' => %w(npo),
        'JOTH' => %w(etc),
        'JREA' => %w(rej),
        'JRNW' => %w(ret),
        'JSCI' => %w(sci),
        'JSEC' => %w(sec),
        'JSKL' => %w(lab trd),
        'JTRA' => %w(trp),
        'JWEB' => %w(eng sof sad web),
        'JWNP' => %w(wri),
        'POTH' => %w(cas msr mis stp),
        'PMSM' => %w(m4m),
        'PMSW' => %w(m4w),
        'PWSM' => %w(w4m),
        'PWSW' => %w(w4w),
        'JRES' => %w(res),
        'SVCP' => %w(trv aos cps cys evs lbs lgs mas rts sks biz),
        'SVCE' => %w(lss),
        'SVCF' => %w(fns),
        'SVCH' => %w(fgs hss),   
        'SVCM' => %w(bts ths thp),  
        'AOTH' => %w(pas)    
      }  

      CHILD_CATEGORIES_FILDS = {
        'AOTH' => { 'data' => %w(price currency status phone), 'annotations' => %w() },
        'APET' => { 'data' => %w(price currency status phone), 'annotations' => %w(make age) },
        'ASUP' => { 'data' => %w(price currency status phone), 'annotations' => nil },
        'C311' => { 'data' => %w(status phone), 'annotations' => nil },
        'C911' => { 'data' => %w(status phone), 'annotations' => nil },
        'COMM' => { 'data' => %w(status phone), 'annotations' => %w(source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'CLNF' => { 'data' => %w(status phone), 'annotations' => nil },
        'CRID' => { 'data' => %w(status phone), 'annotations' => nil },
        'DDEL' => { 'data' => %w(status phone), 'annotations' => nil },
        'DISC' => { 'data' => %w(status phone), 'annotations' => nil },
        'DTAX' => { 'data' => %w(status phone), 'annotations' => nil },
        'DTOW' => { 'data' => %w(status phone), 'annotations' => nil },
        'SANT' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model year source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SAPP' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SAPL' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model vin year source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SANC' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SKID' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SBAR' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SBIK' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model year source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SBIZ' => { 'data' => %w(price currency status phone), 'annotations' => %w(source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SCOL' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model year source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SEDU' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SELE' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model vin year source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SFNB' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SFUR' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SGFT' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SHNB' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SHNG' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SIND' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SJWL' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SLIT' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SMNM' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SMUS' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model year source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SOTH' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SRES' => { 'data' => %w(price currency status phone), 'annotations' => nil },
        'SSNF' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'STIX' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'STOO' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'STOY' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'STVL' => { 'data' => %w(price currency status phone), 'annotations' => nil },
        'SWNT' => { 'data' => %w(price currency status phone), 'annotations' => %w(make model source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'JACC' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JADM' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JAER' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JANL' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JANA' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JARC' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JART' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JAUT' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JBEA' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JBIZ' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JWEB' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JCST' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JCON' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JCUS' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JDES' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JEDU' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JENE' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JENG' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JENT' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JEVE' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JFIN' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JFNB' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JGIG' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JGOV' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JHEA' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JHOS' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JHUM' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JMNT' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JINS' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JINT' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JLAW' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JLEG' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JMAN' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JMFT' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JMAR' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JNON' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JOPS' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JOTH' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JPHA' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JPRO' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JPUR' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JQUA' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JREA' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JREC' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JRES' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JRNW' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JSAL' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JSCI' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JSEC' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JSKL' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JTEL' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JTRA' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JVOL' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'JWNP' => { 'data' => %w(status phone), 'annotations' => %w(compensation part_time telecommute contract internship nonprofit) },
        'MADU' => { 'data' => %w(status phone), 'annotations' => %w(age sex personal_flavor) },
        'MALC' => { 'data' => %w(status phone), 'annotations' => nil },
        'MARM' => { 'data' => %w(status phone), 'annotations' => nil },
        'MDRU' => { 'data' => %w(status phone), 'annotations' => nil },
        'MGAM' => { 'data' => %w(status phone), 'annotations' => nil },
        'MMFM' => { 'data' => %w(status phone), 'annotations' => %w(age sex personal_flavor) },
        'MMFW' => { 'data' => %w(status phone), 'annotations' => %w(age sex personal_flavor) },
        'MOTH' => { 'data' => %w(status phone), 'annotations' => nil },
        'MWFM' => { 'data' => %w(status phone), 'annotations' => %w(age sex personal_flavor) },
        'MWFW' => { 'data' => %w(status phone), 'annotations' => nil }, 
        'ZZZZ' => { 'data' => %w(status phone), 'annotations' => nil },
        'PMSM' => { 'data' => %w(status phone), 'annotations' => %w(age sex personal_flavor) },
        'PMSW' => { 'data' => %w(status phone), 'annotations' => %w(age sex personal_flavor) },
        'POTH' => { 'data' => %w(status phone), 'annotations' => %w(age sex personal_flavor) },
        'PWSM' => { 'data' => %w(status phone), 'annotations' => %w(age sex personal_flavor) },
        'PWSW' => { 'data' => %w(status phone), 'annotations' => %w(age sex personal_flavor) },
        'RCRE' => { 'data' => %w(price currency status phone), 'annotations' => %w(sqft cats dogs year source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date source_map_yahoo source_map_google) },
        'RHFR' => { 'data' => %w(price currency status phone), 'annotations' => %w(bedrooms sqft cats dogs source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'RHFS' => { 'data' => %w(price currency status phone), 'annotations' => %w(bedrooms sqft source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date source_map_yahoo source_map_google) },
        'RSUB' => { 'data' => %w(price currency status phone), 'annotations' => %w(bedrooms sqft cats dogs source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'RSWP' => { 'data' => %w(price currency status phone), 'annotations' => %w(bedrooms sqft cats dogs source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date)  },
        'RLOT' => { 'data' => %w(price currency status phone), 'annotations' => %w(sqft source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'ROTH' => { 'data' => %w(price currency status phone), 'annotations' => %w(sqft source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'RPNS' => { 'data' => %w(price currency status phone), 'annotations' => %w(sqft source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'RSHR' => { 'data' => %w(price currency status phone), 'annotations' => %w(bedrooms sqft cats dogs source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'RVAC' => { 'data' => %w(price currency status phone), 'annotations' => %w(bedrooms sqft cats dogs source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'RWNT' => { 'data' => %w(price currency status phone), 'annotations' => %w(bedrooms sqft cats dogs source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'SVCC' => { 'data' => %w(status phone), 'annotations' => %w(scheduling) },
        'SVCE' => { 'data' => %w(status phone), 'annotations' => %w(scheduling) },
        'SVCF' => { 'data' => %w(status phone), 'annotations' => %w(scheduling) },
        'SVCM' => { 'data' => %w(status phone), 'annotations' => %w(scheduling) },
        'SVCH' => { 'data' => %w(status phone), 'annotations' => %w(scheduling) },
        'SVCO' => { 'data' => %w(status phone), 'annotations' => %w(scheduling) },
        'SVCP' => { 'data' => %w(status phone), 'annotations' => %w(scheduling) },
        'VAUT' => { 'data' => %w(status phone), 'annotations' => %w(make model vin year mileage source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'VOTH' => { 'data' => %w(status phone), 'annotations' => %w(make model vin year mileage source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) },
        'VPAR' => { 'data' => %w(status phone), 'annotations' => %w(make model vin year mileage source_neighborhood source_continent source_state source_loc source_cat source_subcat phone proxy_ip source_account original_posting_date) }
      }
    end
  end
end    